<?php

namespace Database\Seeders;

use App\Models\Tenant\Retention;
use Illuminate\Database\Seeder;

class RetentionSeeder extends Seeder
{
    public function run(): void
    {
        $retentions = [
            // [code, type, description, percentage]
            ['302', 'RENTA', 'Ingresos del trabajo en relación de dependencia', 0.0],
            ['303', 'RENTA', 'Honorarios profesionales y demás pagos por servicios relacionados con el título profesional', 10.0],
            ['303A', 'RENTA', 'Servicios profesionales prestados por sociedades residentes', 5.0],
            ['304', 'RENTA', 'Servicios predomina el intelecto no relacionados con el título profesional', 10.0],
            ['304A', 'RENTA', 'Comisiones y demás pagos por servicios predomina intelecto no relacionados con el título profesional', 10.0],
            ['304B', 'RENTA', 'Pagos a notarios y registradores de la propiedad y mercantil por sus actividades ejercidas como tales', 10.0],
            ['304C', 'RENTA', 'Pagos a deportistas, entrenadores, árbitros, miembros del cuerpo técnico por sus actividades ejercidas como tales', 10.0],
            ['304D', 'RENTA', 'Pagos a artistas por sus actividades ejercidas como tales', 10.0],
            ['304E', 'RENTA', 'Honorarios y demás pagos por servicios de docencia', 10.0],
            ['307', 'RENTA', 'Servicios predomina la mano de obra', 3.0],
            ['308', 'RENTA', 'Utilización o aprovechamiento de la imagen o renombre', 10.0],
            ['309', 'RENTA', 'Servicios prestados por medios de comunicación y agencias de publicidad', 3.0],
            ['310', 'RENTA', 'Servicio de transporte privado de pasajeros o transporte público o privado de carga', 1.0],
            ['311', 'RENTA', 'Pagos a través de liquidación de compra (nivel cultural o rusticidad)', 3.0],
            ['312', 'RENTA', 'Transferencia de bienes muebles de naturaleza corporal', 2.0],
            ['312A', 'RENTA', 'COMPRAS AL PRODUCTOR: de bienes de origen bioacuático, forestal y los descritos el art.27.1 de LRTI', 1.0],
            ['312B', 'RENTA', 'Impuesto a la Renta único para la actividad de producción y cultivo de palma aceitera', 1.0],
            ['312C', 'RENTA', 'COMPRAS AL COMERCIALIZADOR: de bienes de origen bioacuático, forestal y los descritos el art.27.1 de LRTI', 1.75],
            ['314A', 'RENTA', 'Regalías por concepto de franquicias de acuerdo al Código INGENIOS (COESCCI) - pago a personas naturales', 10.0],
            ['314B', 'RENTA', 'Cánones, derechos de autor, marcas, patentes y similares de acuerdo al Código INGENIOS (COESCCI) – pago a personas naturales', 10.0],
            ['314C', 'RENTA', 'Regalías por concepto de franquicias de acuerdo al Código INGENIOS (COESCCI) - pago a sociades', 10.0],
            ['314D', 'RENTA', 'Cánones, derechos de autor, marcas, patentes y similares de acuerdo al Código INGENIOS (COESCCI)', 10.0],
            ['319', 'RENTA', 'Cuotas de arrendamiento mercantil (prestado por sociedades), inclusive la de opción de compra', 2.0],
            ['320', 'RENTA', 'Arrendamiento bienes inmuebles', 10.0],
            ['322', 'RENTA', 'Seguros y reaseguros (primas y cesiones)', 2.0],
            ['323', 'RENTA', 'Rendimientos financieros pagados a naturales y sociedades (No a IFIs)', 3.0],
            ['323A', 'RENTA', 'Rendimientos financieros depósitos Cta. Corriente', 3.0],
            ['323B1', 'RENTA', 'Rendimientos financieros depósitos Cta. Ahorros Sociedades', 3.0],
            ['323E', 'RENTA', 'Rendimientos financieros depósito a plazo fijo gravados', 3.0],
            ['323E2', 'RENTA', 'Rendimientos financieros depósito a plazo fijo exentos', 0.0],
            ['323F', 'RENTA', 'Rendimientos financieros operaciones de reporto repos', 3.0],
            ['323G', 'RENTA', 'Inversiones (captaciones) rendimientos distintos de aquellos pagados a IFIs', 3.0],
            ['323H', 'RENTA', 'Rendimientos financieros obligaciones', 3.0],
            ['323I', 'RENTA', 'Rendimientos financieros bonos convertible en acciones', 3.0],
            ['323 M', 'RENTA', 'Rendimientos financieros: Inversiones en títulos valores en renta fija gravados', 3.0],
            ['323 N', 'RENTA', 'Rendimientos financieros Inversiones en títulos valores en renta fija exentos', 0.0],
            ['323 O', 'RENTA', 'Intereses y demás rendimientos financieros pagados a bancos y otras entidades sometidas al control de la Superintendencia de Bancos y de la Economía Popular y Solidaria', 0.0],
            ['323 P', 'RENTA', 'Intereses pagados por entidades del sector público a favor de sujetos pasivos', 3.0],
            ['323Q', 'RENTA', 'Otros intereses y rendimientos financieros gravados', 3.0],
            ['323R', 'RENTA', 'Otros intereses y rendimientos financieros exentos', 0.0],
            ['323S', 'RENTA', 'Pagos y créditos en cuenta efectuados por el BCE y los depósitos centralizados de valores, en calidad de intermediarios, a instituciones del sistema financiero por cuenta de otras personas naturales y sociedades', 3.0],
            ['323T', 'RENTA', 'Rendimientos financieros originados en la deuda pública ecuatoriana', 0.0],
            ['323U', 'RENTA', 'Rendimientos financieros originados en títulos valores de obligaciones de 360 días o más para el financiamiento de proyectos públicos en asociación público-privada', 0.0],
            ['324A', 'RENTA', 'Intereses en operaciones de crédito entre instituciones del sistema financiero y entidades economía popular y solidaria', 2.0],
            ['324B', 'RENTA', 'Inversiones entre instituciones del sistema financiero y entidades economía popular y solidaria', 2.0],
            ['324C', 'RENTA', 'Pagos y créditos en cuenta efectuados por el BCE y los depósitos centralizados de valores, en calidad de intermediarios, a instituciones del sistema financiero por cuenta de otras instituciones del sistema financiero', 2.0],
            ['325', 'RENTA', 'Anticipo dividendos', 0.0],
            ['325A', 'RENTA', 'Préstamos accionistas, beneficiarios o partícipes residentes o establecidos en el Ecuador', 0.0],
            ['326', 'RENTA', 'Dividendos distribuidos que correspondan al impuesto a la renta único establecido en el art. 27 de la LRTI', 0.0],
            ['327', 'RENTA', 'Dividendos distribuidos a personas naturales residentes', 0.0],
            ['328', 'RENTA', 'Dividendos distribuidos a sociedades residentes', 0.0],
            ['329', 'RENTA', 'Dividendos distribuidos a fideicomisos residentes', 0.0],
            ['331', 'RENTA', 'Dividendos en acciones (capitalización de utilidades)', 0.0],
            ['332', 'RENTA', 'Otras compras de bienes y servicios no sujetas a retención', 0.0],
            ['332B', 'RENTA', 'Compra de bienes inmuebles', 0.0],
            ['332C', 'RENTA', 'Transporte público de pasajeros', 0.0],
            ['332D', 'RENTA', 'Pagos en el país por transporte de pasajeros o transporte internacional de carga, a compañías nacionales o extranjeras de aviación o marítimas', 0.0],
            ['332E', 'RENTA', 'Valores entregados por las cooperativas de transporte a sus socios', 0.0],
            ['332F', 'RENTA', 'Compraventa de divisas distintas al dólar de los Estados Unidos de América', 0.0],
            ['332G', 'RENTA', 'Pagos con tarjeta de crédito', 0.0],
            ['332H', 'RENTA', 'Pago al exterior tarjeta de crédito reportada por la Emisora de tarjeta de crédito, solo recap', 0.0],
            ['332I', 'RENTA', "Pago a través de convenio de debito (Clientes IFI's)", 0.0],
            ['333', 'RENTA', 'Ganancia en la enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades, que se coticen en bolsa de valores del Ecuador', 10.0],
            ['334', 'RENTA', 'Contraprestación producida por la enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades, no cotizados en bolsa de valores del Ecuador', 2.0],
            ['335', 'RENTA', 'Loterías, rifas, apuestas y similares', 15.0],
            ['336', 'RENTA', 'Venta de combustibles a comercializadoras', 0.0],
            ['337', 'RENTA', 'Venta de combustibles a distribuidores', 0.0],
            ['338', 'RENTA', 'Producción y venta local de banano producido o no por el mismo sujeto pasivo', 0.0],
            ['340', 'RENTA', 'Impuesto único a la exportación de banano', 3.0],
            ['343', 'RENTA', 'Otras retenciones aplicables el 1%', 1.0],
            ['343A', 'RENTA', 'Energía eléctrica', 2.0],
            ['343B', 'RENTA', 'Actividades de construcción de obra material inmueble, urbanización, lotización o actividades similares', 2.0],
            ['343C', 'RENTA', 'Recepción de botellas plásticas no retornables de PET', 2.0],
            ['3440', 'RENTA', 'Otras retenciones aplicables el 3%', 3.0],
            ['344A', 'RENTA', 'Pago local tarjeta de crédito, débito reportada por la Emisora de tarjeta de crédito, entidades del sistema financiero', 2.0],
            ['344B', 'RENTA', 'Adquisición de sustancias minerales dentro del territorio nacional', 2.0],
            ['345', 'RENTA', 'Otras retenciones aplicables el 8%', 8.0],
            ['346', 'RENTA', 'Otras retenciones aplicables a otros porcentajes', 1.75],
            ['346A', 'RENTA', 'Otras ganancias de capital distintas de enajenación de derechos representativos de capital', 0.0],
            ['346B', 'RENTA', 'Donaciones en dinero - Impuesto a la donaciones', 0.0],
            ['346C', 'RENTA', 'Retención a cargo del propio sujeto pasivo por la exportación de concentrados y/o elementos metálicos', 0.0],
            ['346D', 'RENTA', 'Retención a cargo del propio sujeto pasivo por la comercialización de productos forestales', 0.0],
            ['348', 'RENTA', 'Impuesto único a ingresos provenientes de actividades agropecuarias en etapa de producción, comercialización local o exportación', 1.0],
            ['350', 'RENTA', 'Otras autorretenciones (inciso 1 y 2 Art.92.1 RLRTI)', 0.0],
            ['351', 'RENTA', 'Régimen microempresarial', 1.75],
            ['3480', 'RENTA', 'Impuesto a la renta único sobre los ingresos percibidos por los operadores de pronósticos deportivos', 15.0],
            ['3482', 'RENTA', 'Comisiones a sociedades, nacionales o extranjeras residentes y establecimientos permanentes domiciliados en el país', 5.0],
            ['500', 'RENTA', 'Pago a no residentes - Rentas Inmobiliarias', 0.0],
            ['501', 'RENTA', 'Pago a no residentes - Beneficios/Servicios Empresariales', 0.0],
            ['501A', 'RENTA', 'Pago a no residentes - Servicios técnicos, administrativos o de consultoría y regalías', 0.0],
            ['503', 'RENTA', 'Pago a no residentes - Navegación Marítima y/o aérea', 0.0],
            ['504', 'RENTA', 'Pago a no residentes - Dividendos distribuidos a personas naturales (domicilados o no en paraiso fiscal) o a sociedades sin beneficiario efectivo persona natural residente en Ecuador', 25.0],
            ['504A', 'RENTA', 'Dividendos a sociedades con beneficiario efectivo persona natural residente en el Ecuador', 0.0],
            ['504B', 'RENTA', 'Dividendos a no residentes incumpliendo el deber de informar la composición societaria', 37.0],
            ['504C', 'RENTA', 'Dividendos a residentes o establecidos en paraísos fiscales o regímenes de menor imposición (con beneficiario Persona Natural residente en Ecuador)', 0.0],
            ['504D', 'RENTA', 'Dividendos a fideicomisos o establecidos en paraísos fiscales o regímenes de menor imposición (con beneficiario Persona Natural residente en Ecuador)', 0.0],
            ['504E', 'RENTA', 'Pago a no residentes - Anticipo dividendos (no domiciliada en paraísos fiscales o regímenes de menor imposición)', 0.0],
            ['504F', 'RENTA', 'Pago a no residentes - Anticipo dividendos (domiciliadas en paraísos fiscales o regímenes de menor imposición)', 0.0],
            ['504G', 'RENTA', 'Pago a no residentes - Préstamos accionistas, beneficiarios o partìcipes (no domiciladas en paraísos fiscales o regímenes de menor imposición)', 0.0],
            ['504H', 'RENTA', 'Pago a no residentes - Préstamos accionistas, beneficiarios o partìcipes (domiciladas en paraísos fiscales o regímenes de menor imposición)', 0.0],
            ['504I', 'RENTA', 'Pago a no residentes - Préstamos no comerciales a partes relacionadas (no domiciladas en paraísos fiscales o regímenes de menor imposición)', 0.0],
            ['504J', 'RENTA', 'Pago a no residentes - Préstamos no comerciales a partes relacionadas (domiciladas en paraísos fiscales o regímenes de menor imposición)', 0.0],
            ['505', 'RENTA', 'Pago a no residentes - Rendimientos financieros', 0.0],
            ['505A', 'RENTA', 'Pago a no residentes – Intereses de créditos de Instituciones Financieras del exterior', 0.0],
            ['505B', 'RENTA', 'Pago a no residentes – Intereses de créditos de gobierno a gobierno', 0.0],
            ['505C', 'RENTA', 'Pago a no residentes – Intereses de créditos de organismos multilaterales', 0.0],
            ['505D', 'RENTA', 'Pago a no residentes - Intereses por financiamiento de proveedores externos', 25.0],
            ['505E', 'RENTA', 'Pago a no residentes - Intereses de otros créditos externos', 25.0],
            ['505F', 'RENTA', 'Pago a no residentes - Otros Intereses y Rendimientos Financieros', 0.0],
            ['509', 'RENTA', 'Pago a no residentes - Cánones, derechos de autor, marcas, patentes y similares', 0.0],
            ['509A', 'RENTA', 'Pago a no residentes - Regalías por concepto de franquicias', 0.0],
            ['510', 'RENTA', 'Pago a no residentes - Otras ganancias de capital distintas de enajenación de derechos representativos de capital', 0.0],
            ['511', 'RENTA', 'Pago a no residentes - Servicios profesionales independientes', 0.0],
            ['512', 'RENTA', 'Pago a no residentes - Servicios profesionales dependientes', 0.0],
            ['513', 'RENTA', 'Pago a no residentes - Artistas', 0.0],
            ['513A', 'RENTA', 'Pago a no residentes - Deportistas', 0.0],
            ['514', 'RENTA', 'Pago a no residentes - Participación de consejeros', 0.0],
            ['515', 'RENTA', 'Pago a no residentes - Entretenimiento Público', 0.0],
            ['516', 'RENTA', 'Pago a no residentes - Pensiones', 0.0],
            ['517', 'RENTA', 'Pago a no residentes - Reembolso de Gastos', 0.0],
            ['518', 'RENTA', 'Pago a no residentes - Funciones Públicas', 0.0],
            ['519', 'RENTA', 'Pago a no residentes - Estudiantes', 0.0],
            ['520A', 'RENTA', 'Pago a no residentes - Pago a proveedores de servicios hoteleros y turísticos en el exterior', 0.0],
            ['520B', 'RENTA', 'Pago a no residentes - Arrendamientos mercantil internacional', 0.0],
            ['520D', 'RENTA', 'Pago a no residentes - Comisiones por exportaciones y por promoción de turismo receptivo', 0.0],
            ['520E', 'RENTA', 'Pago a no residentes - Por las empresas de transporte marítimo o aéreo y por empresas pesqueras de alta mar, por su actividad', 0.0],
            ['520F', 'RENTA', 'Pago a no residentes - Por las agencias internacionales de prensa', 0.0],
            ['520G', 'RENTA', 'Pago a no residentes - Contratos de fletamento de naves para empresas de transporte aéreo o marítimo internacional', 0.0],
            ['521', 'RENTA', 'Pago a no residentes - Enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades', 0.0],
            ['523A', 'RENTA', 'Pago a no residentes - Seguros y reaseguros (primas y cesiones)', 0.0],
            ['525', 'RENTA', 'Pago a no residentes - Donaciones en dinero - Impuesto a la donaciones', 0.0],
            // IVA retentions
            ['9', 'IVA', '10% del IVA causado', 10.0],
            ['10', 'IVA', '20% del IVA causado', 20.0],
            ['1', 'IVA', '30% del IVA causado', 30.0],
            ['11', 'IVA', '50% del IVA causado', 50.0],
            ['2', 'IVA', '70% del IVA causado', 70.0],
            ['3', 'IVA', '100% del IVA causado', 100.0],
        ];

        $rows = array_map(fn ($r) => [
            'code' => $r[0],
            'type' => $r[1],
            'description' => $r[2],
            'percentage' => $r[3],
        ], $retentions);

        foreach (array_chunk($rows, 50) as $chunk) {
            Retention::insert($chunk);
        }
    }
}
